### ISSUE TITLE
give me a hand,please

### ISSUE THREAD

**Issue by machulong** [jindeok/Lottery_Prediction#1]
parser.add_argument('--mode', nargs='?', default='predict', help = "back-test or predict")

Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\Lottery_Prediction-main\Lottery_prediction\main.py", line 40, in <module>
    dataset = DataLoader(args.data_dir, args.training_length, args.window, args.mode)

  File "C:\Users\Administrator\Desktop\Lottery_Prediction-main\Lottery_prediction\data.py", line 23, in __init__
    train_X, test_X, train_y, test_y = self.preproc_entire()

  File "C:\Users\Administrator\Desktop\Lottery_Prediction-main\Lottery_prediction\data.py", line 47, in preproc_entire
    test_X, test_y = test[:, :n_obs], test[:, -ENTIRE_NUMBER:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by jindeok** [comment]
Sorry for the late response!

I think you are trying to index a 1-dimensional array with 2 indices.  
you should 1) check whether you put the data path correctly or 2) investigate the dimension of the 'test' array.
